### ISSUE TITLE
python クラスの継承やオーバーライドについて勉強する

### ISSUE THREAD

**Issue by akihirookuda95** [akihiro-coder/Knowledge-required-for-the-job#2]

**Comment by sagamixaki** [comment]
- [qiita pythonのプロパティのあれこれ](https://qiita.com/cardene/items/8a59d576d360b7568c3a)　これも参考になりそう

**Comment by sagamixaki** [comment]
## 触れていなくて知らないこと
- ダックタイピング
- 抽象クラス
- 多重継承
- 特殊メソッド
- クラスメソッドとスタティックメソッド　等

**Comment by sagamixaki** [comment]
```
super().__init__()
```
の意味と使い方を復習
- [yolov5/models/common.py](https://github.com/ultralytics/yolov5/blob/a4ed9888938a090631ca4dba5be6363f8b66575c/models/common.py#L700)
- [issue#36, yolo_tutorial](https://github.com/ultralytics/yolov5/issues/36)
