### ISSUE TITLE
イテレータについて勉強する

### ISSUE THREAD

**Issue by akihirookuda95** [akihiro-coder/Knowledge-required-for-the-job#4]
- [[Python] イテレータを実装する](https://qiita.com/tchnkmr/items/e740173d7400f8672d75)で理解を図る

**Comment by sagamixaki** [comment]
- 組み込み関数のiter()とnext()関数の使い方を理解した

**Comment by sagamixaki** [comment]
- [イテレータってなに？](https://python.ms/iterator/) この記事が参考になった
- 一通り勉強してみた感覚として、それほど覚えてもメリットが少ないと感じ、他のissueに取り組むことを優先する
- 業務で再度必要になったら上のリンク先等を参考にする
