### ISSUE TITLE
onnxruntimeで推論速度がどれくらい向上するか調査

### ISSUE THREAD

**Issue by akihirookuda95** [akihiro-coder/Knowledge-required-for-the-job#5]
[[ONNXを使って推論速度を高速にしてみる](https://devblog.thebase.in/entry/2019/12/15/110000)](https://devblog.thebase.in/entry/2019/12/15/110000)などを参考に

**Comment by sagamixaki** [comment]
# 知りたいこと
- onnxモデルをonnxruntime上で推論実行したらどれほど速度が向上するか
