### ISSUE TITLE
Yoloモデル関連タスクの勉強

### ISSUE THREAD

**Issue by akihirookuda95** [akihiro-coder/Knowledge-required-for-the-job#9]

**Comment by sagamixaki** [comment]
- yolov5で転移学習を試してみる　⇛　[YOLOv5で転移学習をやってみる](https://kikaben.com/yolov5-transfer-learning/#post-title)
- ~~NMS（後処理）について理解する　⇛　[Non-Maximum Suppression (NMS) ：Bounding Boxの重なり削除方法](https://kikaben.com/non-max-suppression/)~~
- ~~物体検出と画像分類の違いを理解する ⇛　[画像分類と物体検出の違いをはっきり説明します](https://kikaben.com/what-is-object-detection/)~~

**Comment by sagamixaki** [comment]
- アンカーボックスとはなにか理解する　⇛　[ディープ・ラーニングにおける物体検出](https://blogs.sas.com/content/sasjapan/2019/03/12/understanding-object-detection-in-deep-learning/)
